spring.application.name=api

# 1. Cable de conexión a tu contenedor Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/fitnessapp_db
spring.datasource.username=kevin
spring.datasource.password=password123

# 2. Estrategia de creación de tablas (Equivalente al "update" que usábamos antes)
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar el SQL limpio y formateado en la consola de IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
