spring.application.name=api

# 1. Cable de conexión a tu contenedor Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/fitnessapp_db
spring.datasource.username=kevin
spring.datasource.password=password123

# 2. Estrategia de creación de tablas
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar el SQL limpio y formateado en la consola de IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL SMTP)
# ==========================================
# Host: Dirección del servidor de correos oficial de Google al que nos vamos a conectar.
spring.mail.host=smtp.gmail.com

# Port: Puerto estándar de internet por el que se envían los correos de forma cifrada.
spring.mail.port=587

# Username: El correo electrónico que usará tu servidor como cuenta remitente oficial.
spring.mail.username=pizarroguamankevinpaul@gmail.com

# Password: La contraseña de aplicación de 16 dígitos generada en Google (NO tu contraseña real).
spring.mail.password=ewehpsckxnvznlwr

# Auth: Le indica a Java que el servidor de Google le va a pedir iniciar sesión.
spring.mail.properties.mail.smtp.auth=true

# StartTLS: Obliga a que toda la comunicación entre Java y Google esté totalmente encriptada para evitar intercepciones de red (Ciberseguridad básica).
spring.mail.properties.mail.smtp.starttls.enable=true
